development:
  adapter: async

test:
  adapter: async

production:
  adapter: postgresql
  url: ENV[postgres://xlqlcnyniqdtfr:db4cf2bce4a1f0e31d4eceaeee43d0488242c5382936c1b1911214b76e9408a3@ec2-107-22-238-186.compute-1.amazonaws.com:5432/d6l4eevf0st0db]

  channel_prefix: nameofapp_production
# <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
